apiVersion: v1
kind: PersistentVolume
metadata:
  name: My-PV
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
  -  ReadWriteOnce
  storageClassName: nfs
  mountOptions:
  -  hard
  -  nfsvers=4.1
  nfs:
    path: {{ .Values.nfs.path }} 
    server: {{ .Values.nfs.ip }}
