kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.volumes.claimName }}
spec:
  storageClassName: nfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
